### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mickael-kerjean** [rancher/remotedialer#1]
Hello,

Found out about this amazing repo while digging through the code of [inlets](https://github.com/alexellis/inlets) where I was trying to find a way to let unexperienced users for [this project](https://github.com/mickael-kerjean/filestash) expose their own instance on the internet without any knowledge of port forwarding, creation of SSL certificates, ...

That is all amazing, thank you!

**Comment by ibuildthecloud** [comment]
Thanks!
