### ISSUE TITLE
remote dialer does not use proxy env

### ISSUE THREAD

**Issue by chrisbulgaria** [rancher/remotedialer#11]
What kind of request is this (question/bug/enhancement/feature request):
Bug

Steps to reproduce (least amount of steps as possible):
Import existing cluster into Rancher - with a proxy between that cluster and Rancher. Add to the agent yaml the required HTTP_PROXY, HTTPS_PROXY, NO_PROXY envs

Expected : Rancher cluster/node can contact Rancher and import is successful

Result:
Rancher agent wss calls fail, log
time="2019-12-19T09:39:08Z" level=info msg="Connecting to wss://rancher.foobar.com with token $token"
time="2019-12-19T09:39:08Z" level=info msg="Connecting to proxy" url="wss://rancher.foobar.com/v3/connect/register"
time="2019-12-19T09:39:18Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp :443: i/o timeout"
time="2019-12-19T09:39:18Z" level=error msg="Remotedialer proxy error" error="dial tcp $IP_OF_RANCHER:443: i/o timeout"

Other details that may be helpful:
This is the same issue as  rancher repository #24681 and #22750 , its as well the same as #9 in the remotedialer repository sorry for opening a new one, but those are probably not clear enough.
The problem is in remotedialer/client.go line 26
dialer = &websocket.Dialer{HandshakeTimeout:HandshakeTimeOut}
should read instead
dialer = &websocket.Dialer{HandshakeTimeout:HandshakeTimeOut,Proxy: http.ProxyFromEnvironment}

Environment information

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI):
2.3.4 single install

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/24876
