### ISSUE TITLE
Please consider the condition of error printing  buffer exceeded

### ISSUE THREAD

**Issue by w13915984028** [rancher/remotedialer#42]
Refer: https://github.com/harvester/harvester/issues/1956
https://github.com/harvester/harvester/issues/1956#issuecomment-1064993930

`remotedialer buffer exceeded, length: `error message is seen, comparing, the length is in a reasonable range, it does not exceeds 7 MB, not in sky high.

From our test, could you consider error printing when the size is over e.g. 8MB or 16Mb ?
When networking is extremely fast, the paus/resume mechanism may still let the data cached a bit more than expected.

time="2022-03-11T10:29:13Z" level=error msg="remotedialer buffer exceeded, length: 4227072"
time="2022-03-11T10:29:13Z" level=error msg="remotedialer buffer exceeded, length: 4259840"
time="2022-03-11T10:29:13Z" level=error msg="remotedialer buffer exceeded, length: 4292608"
time="2022-03-11T10:29:13Z" level=error msg="remotedialer buffer exceeded, length: 4325376"
..
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4259840"
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4292608"
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4325376"
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4358144"
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4390912"
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4423680"
..
time="2022-03-11T10:29:20Z" level=error msg="remotedialer buffer exceeded, length: 4685824"

Another point:
"remotedialer buffer exceeded" could be an warning or info, error seems too strict, it is self healing.

**Comment by alexellis** [comment]
@w13915984028 the error is now a debug message, can this issue be closed?

**Comment by w13915984028** [comment]
@alexellis we can close it now :)

**Comment by alexellis** [comment]
You would need to do that yourself @w13915984028 

The reason I saw your issue was because I was investigating https://github.com/rancher/remotedialer/issues/57 - where we see a complete lock-up of remotedialer itself - not allowing any connections. Perhaps it's a deadlock?

**Comment by w13915984028** [comment]
close as completed.
