### ISSUE TITLE
[rancher/rancher-agent] Unable to go through proxy

### ISSUE THREAD

**Issue by Wykiki** [rancher/remotedialer#9]
Hello,

I'm running Rancher behind a proxy, and it seems that I cannot tell the Rancher agent WebSocket connection to go through my proxy (nothing in my access log, proxy-side).

I suspect that this library is the cause.

1. Can this library be proxied through an HTTP/S proxy ?
2. Is there environment variable to provide to make it work ?

Thanks for your answers !

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/24876
